export const SECTOR_OPTIONS: { label: string; value: string; labelKey: string }[] = [
  { label: 'Development',            value: 'development',         labelKey: 'missions_page.sec_dev' },
  { label: 'Front-end Development',  value: 'front-end development',labelKey: 'missions_page.sec_frontend' },
  { label: 'Back-end Development',   value: 'back-end development', labelKey: 'missions_page.sec_backend' },
  { label: 'Full Stack Development', value: 'full stack development',labelKey: 'missions_page.sec_fullstack' },
  { label: 'Mobile Development',     value: 'mobile development',   labelKey: 'missions_page.sec_mobile' },
  { label: 'DevOps',                 value: 'devops',               labelKey: 'missions_page.sec_devops' },
  { label: 'Data Science',           value: 'data science',         labelKey: 'missions_page.sec_data' },
  { label: 'Machine Learning / AI',  value: 'machine learning',     labelKey: 'missions_page.sec_ml' },
  { label: 'Cloud Computing',        value: 'cloud computing',      labelKey: 'missions_page.sec_cloud' },
  { label: 'Cybersecurity',          value: 'cybersecurity',        labelKey: 'missions_page.sec_cyber' },
  { label: 'UI/UX Design',           value: 'ui/ux design',         labelKey: 'missions_page.sec_design' },
  { label: 'Graphic Design',         value: 'graphic design',       labelKey: 'missions_page.sec_graphic' },
  { label: 'Project Management',     value: 'project management',   labelKey: 'missions_page.sec_pm' },
  { label: 'QA / Testing',           value: 'qa',                   labelKey: 'missions_page.sec_qa' },
  { label: 'Database Administration',value: 'database',             labelKey: 'missions_page.sec_db' },
  { label: 'Network Engineering',    value: 'network',              labelKey: 'missions_page.sec_network' },
  { label: 'Blockchain',             value: 'blockchain',           labelKey: 'missions_page.sec_blockchain' },
  { label: 'Embedded Systems',       value: 'embedded',             labelKey: 'missions_page.sec_embedded' },
  { label: 'ERP / CRM',              value: 'erp',                  labelKey: 'missions_page.sec_erp' },
  { label: 'Business Intelligence',  value: 'business intelligence',labelKey: 'missions_page.sec_bi' },
  { label: 'Digital Services & IT',  value: 'digital services',     labelKey: 'missions_page.sec_digital' },
  { label: 'Software Publishing',    value: 'software publishing',  labelKey: 'missions_page.sec_software_pub' },
  { label: 'E-commerce',             value: 'e-commerce',           labelKey: 'missions_page.sec_ecommerce' },
  { label: 'Consulting & Audit',     value: 'consulting',           labelKey: 'missions_page.sec_consulting' },
  { label: 'Banking & Finance',      value: 'banking',              labelKey: 'missions_page.sec_banking' },
  { label: 'Healthcare',             value: 'healthcare',           labelKey: 'missions_page.sec_healthcare' },
  { label: 'Telecom',                value: 'telecom',              labelKey: 'missions_page.sec_telecom' },
  { label: 'Education',              value: 'education',            labelKey: 'missions_page.sec_education' },
  { label: 'Industry',               value: 'industry',             labelKey: 'missions_page.sec_industry' },
  { label: 'Media & Entertainment',  value: 'media',                labelKey: 'missions_page.sec_media' },
  { label: 'Real Estate',            value: 'real estate',          labelKey: 'missions_page.sec_realestate' },
  { label: 'Energy',                 value: 'energy',               labelKey: 'missions_page.sec_energy' },
];

export const SPECIALITY_OPTIONS: { label: string; value: string; labelKey?: string }[] = [
  { label: 'React',         value: 'react' },
  { label: 'Angular',       value: 'angular' },
  { label: 'Vue.js',        value: 'vue' },
  { label: 'Java',          value: 'java' },
  { label: 'Spring Boot',   value: 'spring boot' },
  { label: 'Node.js',       value: 'node.js' },
  { label: 'Python',        value: 'python' },
  { label: '.NET',          value: '.net' },
  { label: 'PHP',           value: 'php' },
  { label: 'TypeScript',    value: 'typescript' },
  { label: 'Flutter',       value: 'flutter' },
  { label: 'React Native',  value: 'react native' },
  { label: 'Docker',        value: 'docker' },
  { label: 'Kubernetes',    value: 'kubernetes' },
  { label: 'AWS',           value: 'aws' },
];

export const CATEGORY_OPTIONS: { label: string; value: string; labelKey: string }[] = [
  { label: 'Front-end Developer', value: 'front-end',       labelKey: 'missions_page.cat_frontend' },
  { label: 'Back-end Developer',  value: 'back-end',        labelKey: 'missions_page.cat_backend' },
  { label: 'Full Stack Developer',value: 'full stack',      labelKey: 'missions_page.cat_fullstack' },
  { label: 'Mobile Developer',    value: 'mobile',          labelKey: 'missions_page.cat_mobile' },
  { label: 'Software Engineer',   value: 'software engineer',labelKey: 'missions_page.cat_software_eng' },
  { label: 'DevOps Engineer',     value: 'devops',          labelKey: 'missions_page.cat_devops' },
  { label: 'Data Scientist',      value: 'data',            labelKey: 'missions_page.cat_data' },
  { label: 'UI/UX Designer',      value: 'design',          labelKey: 'missions_page.cat_design' },
  { label: 'Project Manager',     value: 'project manager', labelKey: 'missions_page.cat_pm' },
  { label: 'QA / Tester',         value: 'qa',              labelKey: 'missions_page.cat_qa' },
  { label: 'CMS Developer',       value: 'cms',             labelKey: 'missions_page.cat_cms' },
  { label: 'Web Integrator',      value: 'integrator',      labelKey: 'missions_page.cat_integrator' },
];
