export const SECTOR_OPTIONS: { label: string; value: string }[] = [
  { label: 'Development', value: 'development' },
  { label: 'Front-end Development', value: 'front-end development' },
  { label: 'Back-end Development', value: 'back-end development' },
  { label: 'Full Stack Development', value: 'full stack development' },
  { label: 'Mobile Development', value: 'mobile development' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Data Science', value: 'data science' },
  { label: 'Machine Learning / AI', value: 'machine learning' },
  { label: 'Cloud Computing', value: 'cloud computing' },
  { label: 'Cybersecurity', value: 'cybersecurity' },
  { label: 'UI/UX Design', value: 'ui/ux design' },
  { label: 'Graphic Design', value: 'graphic design' },
  { label: 'Project Management', value: 'project management' },
  { label: 'QA / Testing', value: 'qa' },
  { label: 'Database Administration', value: 'database' },
  { label: 'Network Engineering', value: 'network' },
  { label: 'Blockchain', value: 'blockchain' },
  { label: 'Embedded Systems', value: 'embedded' },
  { label: 'ERP / CRM', value: 'erp' },
  { label: 'Business Intelligence', value: 'business intelligence' },
  { label: 'Digital Services & IT', value: 'digital services' },
  { label: 'Software Publishing', value: 'software publishing' },
  { label: 'E-commerce', value: 'e-commerce' },
  { label: 'Consulting & Audit', value: 'consulting' },
  { label: 'Banking & Finance', value: 'banking' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Telecom', value: 'telecom' },
  { label: 'Education', value: 'education' },
  { label: 'Industry', value: 'industry' },
  { label: 'Media & Entertainment', value: 'media' },
  { label: 'Real Estate', value: 'real estate' },
  { label: 'Energy', value: 'energy' },
];

export const SPECIALITY_OPTIONS: { label: string; value: string }[] = [
  { label: 'React', value: 'react' },
  { label: 'Angular', value: 'angular' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Java', value: 'java' },
  { label: 'Spring Boot', value: 'spring boot' },
  { label: 'Node.js', value: 'node.js' },
  { label: 'Python', value: 'python' },
  { label: '.NET', value: '.net' },
  { label: 'PHP', value: 'php' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'React Native', value: 'react native' },
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'AWS', value: 'aws' },
];

export const CATEGORY_OPTIONS: { label: string; value: string }[] = [
  { label: 'Front-end Developer', value: 'front-end' },
  { label: 'Back-end Developer', value: 'back-end' },
  { label: 'Full Stack Developer', value: 'full stack' },
  { label: 'Mobile Developer', value: 'mobile' },
  { label: 'Software Engineer', value: 'software engineer' },
  { label: 'DevOps Engineer', value: 'devops' },
  { label: 'Data Scientist', value: 'data' },
  { label: 'UI/UX Designer', value: 'design' },
  { label: 'Project Manager', value: 'project manager' },
  { label: 'QA / Tester', value: 'qa' },
  { label: 'CMS Developer', value: 'cms' },
  { label: 'Web Integrator', value: 'integrator' },
];
