export enum Role {
  FREELANCER = 'FREELANCER',
  COMPANY = 'COMPANY',
  ADMIN = 'ADMIN',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum ProfileType {
  BI_DATA = 'BI_DATA',
  BUSINESS_CONSULTING = 'BUSINESS_CONSULTING',
  ERP_CRM = 'ERP_CRM',
  INDUSTRIAL_IT_ELECTRONICS = 'INDUSTRIAL_IT_ELECTRONICS',
  NEW_TECHNOLOGIES = 'NEW_TECHNOLOGIES',
  OFFICE_SUPPORT = 'OFFICE_SUPPORT',
  TESTING_QUALITY = 'TESTING_QUALITY',
  SYSTEM_RESOURCES = 'SYSTEM_RESOURCES',
  STUDIES_DEVELOPMENT = 'STUDIES_DEVELOPMENT',
  SYSTEMS_INFRASTRUCTURE = 'SYSTEMS_INFRASTRUCTURE',
  OTHER = 'OTHER',
}

export enum Language {
  FRENCH = 'FRENCH',
  ENGLISH = 'ENGLISH',
  ARABIC = 'ARABIC',
  SPANISH = 'SPANISH',
  GERMAN = 'GERMAN',
  ITALIAN = 'ITALIAN',
  PORTUGUESE = 'PORTUGUESE',
  CHINESE = 'CHINESE',
  JAPANESE = 'JAPANESE',
  OTHER = 'OTHER',
}

export enum LegalForm {
  SARL = 'SARL',
  SAS = 'SAS',
  PAS = 'PAS',
  SUARL = 'SUARL',
  OTHER = 'OTHER',
}

export enum CompanyStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
