export type NotificationType =
  | 'WELCOME'
  | 'APPLICATION_SUBMITTED'
  | 'APPLICATION_ACCEPTED'
  | 'APPLICATION_REJECTED'
  | 'APPLICATION_WITHDRAWN'
  | 'NEW_MISSION_MATCH'
  | 'MISSION_DEADLINE_SOON'
  | 'PROFILE_INCOMPLETE'
  | 'COMPANY_WELCOME'
  | 'MISSION_PUBLISHED'
  | 'APPLICATION_RECEIVED'
  | 'PENDING_APPLICATIONS_REMINDER'
  | 'MISSION_CLOSED'
  | 'CONTRACT_GENERATED'
  | 'CONTRACT_SIGNED'
  | 'CONTRACT_SIGNATURE_REMINDER'
  | 'CONTRACT_REJECTED'
  | 'MISSION_SUBMITTED'
  | 'MISSION_VALIDATED'
  | 'MISSION_ACTIVATED'
  | 'COMPANY_PENDING_VERIFICATION'
  | 'COMPANY_APPROVED'
  | 'COMPANY_REJECTED'
  | 'MISSION_DELETED_BY_ADMIN'
  | 'CONTRACT_CANCELLED_BY_ADMIN'
  | 'FEEDBACK_VALIDATED'
  | 'FEEDBACK_REJECTED'
  | 'ADMIN_COMPANY_VERIFICATION_REQUEST'
  | 'ADMIN_NEW_FREELANCER_REGISTERED'
  | 'ADMIN_NEW_CONTRACT_SIGNED'
  | 'ADMIN_NEW_MISSION_PUBLISHED';

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  senderName: string;
  senderId?: string;
  isRead: boolean;
  createdAt: string;
  actionUrl?: string;
}
